-- MySQL Script generated by MySQL Workbench
-- 10/03/17 22:42:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema lapd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `lapd` ;

-- -----------------------------------------------------
-- Schema lapd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lapd` DEFAULT CHARACTER SET utf8 ;
USE `lapd` ;

-- -----------------------------------------------------
-- Table `lapd`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lapd`.`admin` ;

CREATE TABLE IF NOT EXISTS `lapd`.`admin` (
  `idAdmin` VARCHAR(15) NOT NULL,
  `password` VARCHAR(15) NOT NULL,
  `addTime` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idAdmin`),
  UNIQUE INDEX `idadmin_UNIQUE` (`idAdmin` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lapd`.`roomcatagory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lapd`.`roomcatagory` ;

CREATE TABLE IF NOT EXISTS `lapd`.`roomcatagory` (
  `number` INT NULL COMMENT '序号',
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `index_UNIQUE` (`number` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lapd`.`clockcatagory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lapd`.`clockcatagory` ;

CREATE TABLE IF NOT EXISTS `lapd`.`clockcatagory` (
  `number` INT NULL COMMENT '序号',
  `name` VARCHAR(20) NOT NULL COMMENT '上钟类型',
  PRIMARY KEY (`name`),
  UNIQUE INDEX `index_UNIQUE` (`number` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lapd`.`paypath`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lapd`.`paypath` ;

CREATE TABLE IF NOT EXISTS `lapd`.`paypath` (
  `number` INT NULL COMMENT '序号',
  `payPath` VARCHAR(20) NOT NULL COMMENT '支付方式',
  PRIMARY KEY (`payPath`),
  UNIQUE INDEX `index_UNIQUE` (`number` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lapd`.`pledge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lapd`.`pledge` ;

CREATE TABLE IF NOT EXISTS `lapd`.`pledge` (
  `number` INT NULL COMMENT '序号',
  `name` VARCHAR(20) NOT NULL COMMENT '所借用物品的名字',
  `price` INT(11) NULL COMMENT '借用物品的价格',
  PRIMARY KEY (`name`),
  UNIQUE INDEX `price_UNIQUE` (`price` ASC),
  UNIQUE INDEX `index_UNIQUE` (`number` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lapd`.`room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lapd`.`room` ;

CREATE TABLE IF NOT EXISTS `lapd`.`room` (
  `idRoom` VARCHAR(10) NOT NULL COMMENT '房间编号',
  `catagory` VARCHAR(45) NULL DEFAULT NULL COMMENT '房间名字',
  `floor` INT(11) NULL DEFAULT NULL,
  `size` INT(11) NULL DEFAULT NULL COMMENT '房间可容纳客人的人数',
  `remark` VARCHAR(255) NULL DEFAULT NULL COMMENT '房间描述',
  `addTime` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idRoom`),
  INDEX `name_idx` (`catagory` ASC),
  CONSTRAINT `name`
    FOREIGN KEY (`catagory`)
    REFERENCES `lapd`.`roomcatagory` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lapd`.`workstatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lapd`.`workstatus` ;

CREATE TABLE IF NOT EXISTS `lapd`.`workstatus` (
  `number` INT NULL COMMENT '序号',
  `workStatus` VARCHAR(20) NOT NULL COMMENT '工作状态',
  PRIMARY KEY (`workStatus`),
  UNIQUE INDEX `index_UNIQUE` (`number` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lapd`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lapd`.`user` ;

CREATE TABLE IF NOT EXISTS `lapd`.`user` (
  `idUser` VARCHAR(45) NOT NULL COMMENT '员工编号',
  `password` VARCHAR(45) NOT NULL COMMENT '员工密码',
  `id` INT(11) NULL DEFAULT NULL COMMENT '员工的工作id',
  `birthday` DATE NULL DEFAULT NULL COMMENT '出生日期',
  `telPhone` VARCHAR(15) NULL DEFAULT NULL COMMENT '电话号码',
  `email` VARCHAR(20) NULL DEFAULT NULL COMMENT '电子邮件',
  `address` VARCHAR(200) NULL DEFAULT NULL COMMENT '地址',
  `imagePath` VARCHAR(255) NULL DEFAULT NULL COMMENT '头像图片路径',
  `question` VARCHAR(20) NOT NULL COMMENT '密保问题',
  `answer` VARCHAR(100) NULL DEFAULT NULL COMMENT '密保答案',
  `workStatus` VARCHAR(20) NULL DEFAULT NULL,
  `addTime` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `workStatus_idx` (`workStatus` ASC),
  CONSTRAINT `UserworkStatus`
    FOREIGN KEY (`workStatus`)
    REFERENCES `lapd`.`workstatus` (`workStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lapd`.`orderstatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lapd`.`orderstatus` ;

CREATE TABLE IF NOT EXISTS `lapd`.`orderstatus` (
  `number` INT NULL COMMENT '序号',
  `orderstatus` VARCHAR(20) NOT NULL COMMENT '订单类型',
  PRIMARY KEY (`orderstatus`),
  UNIQUE INDEX `index_UNIQUE` (`number` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lapd`.`serverorder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lapd`.`serverorder` ;

CREATE TABLE IF NOT EXISTS `lapd`.`serverorder` (
  `idUser` VARCHAR(45) NOT NULL COMMENT '员工编号',
  `id` INT(11) NOT NULL COMMENT '员工工作编号',
  `idRoom` VARCHAR(10) NOT NULL COMMENT '所在房间编号',
  `idOrder` VARCHAR(45) NOT NULL COMMENT '订单编号',
  `status` VARCHAR(20) NOT NULL COMMENT '订单状态',
  `addTime` DATETIME NULL DEFAULT NULL COMMENT '开单时间',
  `startTime` DATETIME NULL DEFAULT NULL COMMENT '此服务单开始时间',
  `endTime` DATETIME NULL DEFAULT NULL COMMENT '此服务单结束时间',
  `pay` INT(11) NULL DEFAULT '0' COMMENT '应付金额',
  `realPay` INT(11) NULL DEFAULT '0' COMMENT '实付金额',
  `payTime` DATETIME NULL DEFAULT NULL,
  `orderRemark` VARCHAR(255) NULL DEFAULT NULL COMMENT '订单描述',
  `payPath` VARCHAR(10) NULL DEFAULT NULL COMMENT '支付途径',
  `pledgeName` VARCHAR(20) NULL DEFAULT NULL COMMENT '所压物品',
  `pledgePrice` INT(11) NULL DEFAULT '0' COMMENT '押金金额',
  `clockcatagory` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idOrder`),
  UNIQUE INDEX `idOrder_UNIQUE` (`idOrder` ASC),
  INDEX `idRoom_idx` (`idRoom` ASC),
  INDEX `id_idx` (`id` ASC),
  INDEX `payPath_idx` (`payPath` ASC),
  INDEX `pledgeName_idx` (`pledgeName` ASC),
  INDEX `clockcatagory_idx` (`clockcatagory` ASC),
  INDEX `idUser` (`idUser` ASC),
  INDEX `orderstatus_idx` (`status` ASC),
  CONSTRAINT `clockcatagory`
    FOREIGN KEY (`clockcatagory`)
    REFERENCES `lapd`.`clockcatagory` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`id`)
    REFERENCES `lapd`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idRoom`
    FOREIGN KEY (`idRoom`)
    REFERENCES `lapd`.`room` (`idRoom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `lapd`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `payPath`
    FOREIGN KEY (`payPath`)
    REFERENCES `lapd`.`paypath` (`payPath`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pledgeName`
    FOREIGN KEY (`pledgeName`)
    REFERENCES `lapd`.`pledge` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `orderstatus`
    FOREIGN KEY (`status`)
    REFERENCES `lapd`.`orderstatus` (`orderstatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lapd`.`workrank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lapd`.`workrank` ;

CREATE TABLE IF NOT EXISTS `lapd`.`workrank` (
  `id` INT(11) NOT NULL COMMENT '员工的工作牌号\n',
  `rankNum` INT(11) NULL DEFAULT '0' COMMENT '排钟数量',
  `spotNum` INT(11) NULL DEFAULT '0' COMMENT '点钟数量',
  INDEX `id_user_idx` (`id` ASC),
  CONSTRAINT `id_user`
    FOREIGN KEY (`id`)
    REFERENCES `lapd`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
