-- MySQL Script generated by MySQL Workbench
-- 08/09/17 22:27:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lapd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `lapd` ;

-- -----------------------------------------------------
-- Schema lapd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lapd` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `lapd` ;

-- -----------------------------------------------------
-- Table `lapd`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lapd`.`admin` ;

CREATE TABLE IF NOT EXISTS `lapd`.`admin` (
  `idAdmin` VARCHAR(15) NOT NULL,
  `password` VARCHAR(15) NOT NULL,
  `addTime` DATE NULL,
  PRIMARY KEY (`idAdmin`),
  UNIQUE INDEX `idadmin_UNIQUE` (`idAdmin` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lapd`.`workstatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lapd`.`workstatus` ;

CREATE TABLE IF NOT EXISTS `lapd`.`workstatus` (
  `workStatus` VARCHAR(20) NOT NULL COMMENT '工作状态',
  PRIMARY KEY (`workStatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lapd`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lapd`.`user` ;

CREATE TABLE IF NOT EXISTS `lapd`.`user` (
  `idUser` VARCHAR(45) NOT NULL COMMENT '员工编号',
  `password` VARCHAR(45) NOT NULL COMMENT '员工密码',
  `id` INT NULL COMMENT '员工的工作id',
  `birthday` DATE NULL COMMENT '出生日期',
  `telPhone` VARCHAR(15) NULL COMMENT '电话号码',
  `email` VARCHAR(20) NULL COMMENT '电子邮件',
  `address` VARCHAR(200) NULL COMMENT '地址',
  `imagePath` VARCHAR(255) NULL COMMENT '头像图片路径',
  `question` VARCHAR(20) NOT NULL COMMENT '密保问题',
  `answer` VARCHAR(100) NULL COMMENT '密保答案',
  `workStatus` VARCHAR(20) NULL,
  `addTime` DATETIME NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `workStatus_idx` (`workStatus` ASC),
  CONSTRAINT `workStatus`
    FOREIGN KEY (`workStatus`)
    REFERENCES `lapd`.`workstatus` (`workStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lapd`.`catagory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lapd`.`catagory` ;

CREATE TABLE IF NOT EXISTS `lapd`.`catagory` (
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lapd`.`room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lapd`.`room` ;

CREATE TABLE IF NOT EXISTS `lapd`.`room` (
  `idRoom` VARCHAR(10) NOT NULL COMMENT '房间编号',
  `catagory` VARCHAR(45) NULL COMMENT '房间名字',
  `floor` INT NULL,
  `size` INT NULL COMMENT '房间可容纳客人的人数',
  `remark` VARCHAR(255) NULL COMMENT '房间描述',
  `addTime` DATETIME NULL,
  PRIMARY KEY (`idRoom`),
  INDEX `name_idx` (`catagory` ASC),
  CONSTRAINT `name`
    FOREIGN KEY (`catagory`)
    REFERENCES `lapd`.`catagory` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lapd`.`paypath`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lapd`.`paypath` ;

CREATE TABLE IF NOT EXISTS `lapd`.`paypath` (
  `payPath` VARCHAR(20) NOT NULL COMMENT '支付方式',
  PRIMARY KEY (`payPath`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lapd`.`pledge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lapd`.`pledge` ;

CREATE TABLE IF NOT EXISTS `lapd`.`pledge` (
  `name` VARCHAR(20) NOT NULL COMMENT '所借用物品的名字',
  `price` INT NULL COMMENT '借用物品的价格',
  PRIMARY KEY (`name`),
  UNIQUE INDEX `price_UNIQUE` (`price` ASC))
ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS `lapd`.`clockcatagory` (
  `name` VARCHAR(20) NOT NULL COMMENT '上钟类型',
  PRIMARY KEY (`name`))
ENGINE = InnoDB


go
DROP TRIGGER IF EXISTS serverorder_AFTER_UPDATE;
go
go
CREATE TRIGGER serverorder_AFTER_UPDATE AFTER UPDATE ON serverorder
FOR EACH ROW
BEGIN
	DECLARE num int ; 
	if(old.status = '待员工确定' and new.status = '服务中') then
		 if(old.id not in (select id from workrank )) then
		 	if (old.clockcatagory <> '点钟') then
			 	insert into workrank values (old.id, 1, 0);
			else
			 	insert into workrank values (old.id, 0, 1);
			end if;
         elseif (old.clockcatagory <> '点钟') then 
			set num = (select rankNum from workrank where workrank.id = old.id);
            update workrank set rankNum = num + 1 where workrank.id = old.id;
		 else
			set num = (select spotNum from workrank where workrank.id = old.id);
            update workrank set spotNum = num + 1 where workrank.id = old.id;
		 end if;
    end if;
END
go







drop table if exists `lapd`.`serverorder`;
CREATE TABLE IF NOT EXISTS `lapd`.`serverorder` (
  `idUser` VARCHAR(45) NOT NULL COMMENT '员工编号',
  `id` INT NOT NULL COMMENT '员工工作编号',
  `idRoom` VARCHAR(10) NOT NULL COMMENT '所在房间编号',
  `idOrder` VARCHAR(45) NOT NULL COMMENT '订单编号',
  `status` varchar(20) NOT NULL COMMENT '订单状态',
  `addTime` DATETIME NULL COMMENT '开单时间',
  `startTime` DATETIME NULL COMMENT '此服务单开始时间',
  `endTime` DATETIME NULL COMMENT '此服务单结束时间',
  `pay` INT NULL DEFAULT 0 COMMENT '应付金额',
  `realPay` INT DEFAULT 0 NULL COMMENT '实付金额',
  `payTime` DATETIME NULL,
  `orderRemark` VARCHAR(255) NULL COMMENT '订单描述',
  `payPath` VARCHAR(10) NULL COMMENT '支付途径',
  `pledgeName` VARCHAR(20) NULL COMMENT '所压物品',
  `pledgePrice` INT NULL DEFAULT 0 COMMENT '押金金额',
  `clockcatagory` VARCHAR(20) NULL,
  INDEX `idRoom_idx` (`idRoom` ASC),
  INDEX `id_idx` (`id` ASC),
  UNIQUE INDEX `idOrder_UNIQUE` (`idOrder` ASC),
  INDEX `payPath_idx` (`payPath` ASC),
  INDEX `pledgeName_idx` (`pledgeName` ASC),
  PRIMARY KEY (`idOrder`),
  INDEX `clockcatagory_idx` (`clockcatagory` ASC),
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `lapd`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`id`)
    REFERENCES `lapd`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idRoom`
    FOREIGN KEY (`idRoom`)
    REFERENCES `lapd`.`room` (`idRoom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `payPath`
    FOREIGN KEY (`payPath`)
    REFERENCES `lapd`.`paypath` (`payPath`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pledgeName`
    FOREIGN KEY (`pledgeName`)
    REFERENCES `lapd`.`pledge` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `clockcatagory`
    FOREIGN KEY (`clockcatagory`)
    REFERENCES `lapd`.`clockcatagory` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `lapd`.`workrank` (
  `id` INT NOT NULL,
  `rankNum` INT NULL DEFAULT 0,
  `spotNum` INT NULL DEFAULT 0
/*   UNIQUE INDEX `id_UNIQUE_wr` (`id` ASC),
  
  PRIMARY KEY (`id`),
  CONSTRAINT `id`
    FOREIGN KEY (`id`)
    REFERENCES `lapd`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION */)
ENGINE = InnoDB

select * from workrank;

-- -----------------------------------------------------
-- Table `lapd`.`workrank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lapd`.`workrank` ;

CREATE TABLE IF NOT EXISTS `lapd`.`workrank` (
  `id` INT NULL,
  `rankNum` INT NULL DEFAULT 0,
  `spotNum` INT NULL DEFAULT 0)
  	CONSTRAINT `id`
 	FOREIGN KEY (`id`)
    REFERENCES `lapd`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
